Cypress.Commands.add('adminLogin', (url) => {
	cy.visit( url )
	cy.wait(500)
	cy.get('#user_login')
		.focus()
		.type(Cypress.env('admin_user'))
	cy.get('#user_pass')
		.focus()
		.type(Cypress.env('admin_pass'))
	cy.get('#wp-submit').click()
})

Cypress.Commands.add('customerLogin', (url) => {
	cy.visit( '/wp-login.php?redirect_to=' + encodeURI( url ) )
	cy.wait(500)
	cy.get('#user_login')
		.focus()
		.type(Cypress.env('customer_user'))
	cy.get('#user_pass')
		.focus()
		.type(Cypress.env('customer_pass'))
	cy.get('#wp-submit').click()
})
