Cypress.Commands.add('login', (url) => {
	cy.visit( url )
	cy.wait(500)
	cy.get('#user_login')
		.focus()
		.type(Cypress.env('admin_user'))
	cy.get('#user_pass')
		.focus()
		.type(Cypress.env('admin_pass'))
	cy.get('#wp-submit').click()
})
